name: holidrive
description: An application to improve public mobility.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.6.6'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  provider: ^6.0.5
  fluttertoast: ^8.2.2
  get: ^4.6.6
  google_maps_flutter: ^2.5.0
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1
  font_awesome_flutter: ^10.5.0
  cloud_firestore: ^4.9.1
  json_annotation: ^4.8.1
  google_sign_in: ^6.1.5
  firebase_storage: ^11.2.6
  location: ^5.0.3
  firebase_database: ^10.2.6
  file_picker: ^5.5.0
  custom_info_window: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  dotted_border: ^2.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  uuid: ^4.1.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  adaptative_icon_background: '#ffffff'
  adaptative_icon_foreground: 'assets/core/marker-logo.png'
  image_path: 'assets/core/icon.png'
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/core/
    - assets/map/

  fonts:
    - family: Catamaran
      fonts:
        - asset: fonts/Catamaran-Regular.ttf
        - asset: fonts/Catamaran-Medium.ttf
          weight: 500
        - asset: fonts/Catamaran-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
